export const CURRENCY_SYMBOLS: { [key: string]: string } = {
  'USD': '$',
  'EUR': '€',
  'GBP': '£',
  'JPY': '¥',
  'INR': '₹',
  'CNY': '¥',
  'KRW': '₩',
  'RUB': '₽',
  'BRL': 'R$',
  'CAD': 'C$',
  'AUD': 'A$',
  'CHF': 'Fr',
  'HKD': 'HK$',
  'SGD': 'S$',
  'SEK': 'kr',
  'NZD': 'NZ$',
  'MXN': '$',
  'AED': 'د.إ',
  'THB': '฿',
  'ZAR': 'R',
};
